/** @type {import('tailwindcss/tailwind-config').TailwindConfig} */

module.exports = {
  content: ['./src/**/*.{jsx,js,tsx,ts}'],
  theme: {
    colors: {
      black: 'var(--bq-black)',
      white: 'var(--bq-white)',
      blue: {
        1: 'var(--bq-blue-1)',
        2: 'var(--bq-blue-2)',
        3: 'var(--bq-blue-3)',
        4: 'var(--bq-blue-4)',
        5: 'var(--bq-blue-5)',
        6: 'var(--bq-blue-6)',
        7: 'var(--bq-blue-7)',
        8: 'var(--bq-blue-8)',
        9: 'var(--bq-blue-9)',
        10: 'var(--bq-blue-10)',
      },
      corai: {
        1: 'var(--bq-corai-1)',
        2: 'var(--bq-corai-2)',
        3: 'var(--bq-corai-3)',
        4: 'var(--bq-corai-4)',
        5: 'var(--bq-corai-5)',
        6: 'var(--bq-corai-6)',
        7: 'var(--bq-corai-7)',
        8: 'var(--bq-corai-8)',
        9: 'var(--bq-corai-9)',
        10: 'var(--bq-corai-10)',
      },
      cyan: {
        1: 'var(--bq-cyan-1)',
        2: 'var(--bq-cyan-2)',
        3: 'var(--bq-cyan-3)',
        4: 'var(--bq-cyan-4)',
        5: 'var(--bq-cyan-5)',
        6: 'var(--bq-cyan-6)',
        7: 'var(--bq-cyan-7)',
        8: 'var(--bq-cyan-8)',
        9: 'var(--bq-cyan-9)',
        10: 'var(--bq-cyan-10)',
      },
      geekblue: {
        1: 'var(--bq-geekblue-1)',
        2: 'var(--bq-geekblue-2)',
        3: 'var(--bq-geekblue-3)',
        4: 'var(--bq-geekblue-4)',
        5: 'var(--bq-geekblue-5)',
        6: 'var(--bq-geekblue-6)',
        7: 'var(--bq-geekblue-7)',
        8: 'var(--bq-geekblue-8)',
        9: 'var(--bq-geekblue-9)',
        10: 'var(--bq-geekblue-10)',
      },
      gold: {
        1: 'var(--bq-gold-1)',
        2: 'var(--bq-gold-2)',
        3: 'var(--bq-gold-3)',
        4: 'var(--bq-gold-4)',
        5: 'var(--bq-gold-5)',
        6: 'var(--bq-gold-6)',
        7: 'var(--bq-gold-7)',
        8: 'var(--bq-gold-8)',
        9: 'var(--bq-gold-9)',
        10: 'var(--bq-gold-10)',
      },
      green: {
        1: 'var(--bq-green-1)',
        2: 'var(--bq-green-2)',
        3: 'var(--bq-green-3)',
        4: 'var(--bq-green-4)',
        5: 'var(--bq-green-5)',
        6: 'var(--bq-green-6)',
        7: 'var(--bq-green-7)',
        8: 'var(--bq-green-8)',
        9: 'var(--bq-green-9)',
        10: 'var(--bq-green-10)',
      },
      grey: {
        1: 'var(--bq-grey-1)',
        2: 'var(--bq-grey-2)',
        3: 'var(--bq-grey-3)',
        4: 'var(--bq-grey-4)',
        5: 'var(--bq-grey-5)',
        6: 'var(--bq-grey-6)',
        7: 'var(--bq-grey-7)',
        8: 'var(--bq-grey-8)',
        9: 'var(--bq-grey-9)',
        10: 'var(--bq-grey-10)',
      },
      lime: {
        1: 'var(--bq-lime-1)',
        2: 'var(--bq-lime-2)',
        3: 'var(--bq-lime-3)',
        4: 'var(--bq-lime-4)',
        5: 'var(--bq-lime-5)',
        6: 'var(--bq-lime-6)',
        7: 'var(--bq-lime-7)',
        8: 'var(--bq-lime-8)',
        9: 'var(--bq-lime-9)',
        10: 'var(--bq-lime-10)',
      },
      magenta: {
        1: 'var(--bq-magenta-1)',
        2: 'var(--bq-magenta-2)',
        3: 'var(--bq-magenta-3)',
        4: 'var(--bq-magenta-4)',
        5: 'var(--bq-magenta-5)',
        6: 'var(--bq-magenta-6)',
        7: 'var(--bq-magenta-7)',
        8: 'var(--bq-magenta-8)',
        9: 'var(--bq-magenta-9)',
        10: 'var(--bq-magenta-10)',
      },
      orange: {
        1: 'var(--bq-orange-1)',
        2: 'var(--bq-orange-2)',
        3: 'var(--bq-orange-3)',
        4: 'var(--bq-orange-4)',
        5: 'var(--bq-orange-5)',
        6: 'var(--bq-orange-6)',
        7: 'var(--bq-orange-7)',
        8: 'var(--bq-orange-8)',
        9: 'var(--bq-orange-9)',
        10: 'var(--bq-orange-10)',
      },
      purple: {
        1: 'var(--bq-purple-1)',
        2: 'var(--bq-purple-2)',
        3: 'var(--bq-purple-3)',
        4: 'var(--bq-purple-4)',
        5: 'var(--bq-purple-5)',
        6: 'var(--bq-purple-6)',
        7: 'var(--bq-purple-7)',
        8: 'var(--bq-purple-8)',
        9: 'var(--bq-purple-9)',
        10: 'var(--bq-purple-10)',
      },
      red: {
        1: 'var(--bq-red-1)',
        2: 'var(--bq-red-2)',
        3: 'var(--bq-red-3)',
        4: 'var(--bq-red-4)',
        5: 'var(--bq-red-5)',
        6: 'var(--bq-red-6)',
        7: 'var(--bq-red-7)',
        8: 'var(--bq-red-8)',
        9: 'var(--bq-red-9)',
        10: 'var(--bq-red-10)',
      },
      teal: {
        1: 'var(--bq-teal-1)',
        2: 'var(--bq-teal-2)',
        3: 'var(--bq-teal-3)',
        4: 'var(--bq-teal-4)',
        5: 'var(--bq-teal-5)',
        6: 'var(--bq-teal-6)',
        7: 'var(--bq-teal-7)',
        8: 'var(--bq-teal-8)',
        9: 'var(--bq-teal-9)',
        10: 'var(--bq-teal-10)',
      },
      volcano: {
        1: 'var(--bq-volcano-1)',
        2: 'var(--bq-volcano-2)',
        3: 'var(--bq-volcano-3)',
        4: 'var(--bq-volcano-4)',
        5: 'var(--bq-volcano-5)',
        6: 'var(--bq-volcano-6)',
        7: 'var(--bq-volcano-7)',
        8: 'var(--bq-volcano-8)',
        9: 'var(--bq-volcano-9)',
        10: 'var(--bq-volcano-10)',
      },
      yellow: {
        1: 'var(--bq-yellow-1)',
        2: 'var(--bq-yellow-2)',
        3: 'var(--bq-yellow-3)',
        4: 'var(--bq-yellow-4)',
        5: 'var(--bq-yellow-5)',
        6: 'var(--bq-yellow-6)',
        7: 'var(--bq-yellow-7)',
        8: 'var(--bq-yellow-8)',
        9: 'var(--bq-yellow-9)',
        10: 'var(--bq-yellow-10)',
      },
    },
    extend: {},
  },
  plugins: [],
  corePlugins: {
    preflight: false,
  },
};
