export const DefaultRootTheme = {
  // Border Radius
  'bq-radius--none': '0',
  'bq-radius--xs2': '0.125rem',
  'bq-radius--xs': '0.25rem',
  'bq-radius--s': '0.5rem',
  'bq-radius--m': '0.75rem',
  'bq-radius--l': '1.5rem',
  'bq-radius--full': '9999px',
  // Box Shadow
  'bq-box-shadow--xs': '0 2px 0 rgba(0, 0, 0, 0.016)',
  'bq-box-shadow--s': '0 8px 24px rgba(0, 0, 0, 0.04)',
  'bq-box-shadow--m': '0 10px 48px -16px rgba(0, 0, 0, 0.12)',
  'bq-box-shadow--l': '0 20px 58px -16px rgba(0, 0, 0, 0.16)',
  // Fonts
  'bq-font-family--outfit': "'Outfit', sans-serif",
  'bq-font-size--xs': '0.75rem',
  'bq-font-size--s': '0.875rem',
  'bq-font-size--m': '1rem',
  'bq-font-size--l': '1.125rem',
  'bq-font-size--xl': '1.5rem',
  'bq-font-size--xxl': '2rem',
  'bq-font-size--xxl2': '2.5rem',
  'bq-font-size--xxl3': '3rem',
  'bq-font-size--xxl4': '3.5rem',
  'bq-font-size--xxl5': '4rem',
  'bq-font-weight--thin': '100',
  'bq-font-weight--light': '300',
  'bq-font-weight--regular': '400',
  'bq-font-weight--medium': '500',
  'bq-font-weight--semibold': '600',
  'bq-font-weight--bold': '700',
  'bq-font-line-height--small': '1.2',
  'bq-font-line-height--regular': '1.5',
  'bq-font-line-height--large': '1.5',
  // Spacing
  'bq-spacing-xs3': '0.125rem',
  'bq-spacing-xs2': '0.25rem',
  'bq-spacing-xs': '0.5rem',
  'bq-spacing-s': '0.75rem',
  'bq-spacing-m': '1rem',
  'bq-spacing-l': '1.5rem',
  'bq-spacing-xl': '2rem',
  'bq-spacing-xxl': '2.5rem',
  'bq-spacing-xxl2': '3.5rem',
  'bq-spacing-xxl3': '4rem',
  'bq-spacing-xxl4': '4.5rem',
};
