linkWorkspacePackages: true
preferFrozenLockfile: true
provenance: true
saveExact: true

packages:
  - 'apps/*'
  - 'packages/*'

allowBuilds:
  '@parcel/watcher': false
  '@swc/core': true
  'core-js': true
  'esbuild': false
  'less': false
  'lmdb': false
  'msgpackr-extract': false
  'nx': true
  'rs-module-lexer': false
  'unrs-resolver': false

overrides:
  '@angular-devkit/core': '22.0.8'
  '@angular-devkit/schematics': '22.0.8'
  '@custom-elements-manifest/analyzer': '0.11.0'
  '@module-federation/enhanced': '0.22.0'
  '@schematics/angular': '22.0.8'
  'ng-packagr': '22.0.2'
  'node-fetch': '3.3.2'
  'nx': '23.1.0'
  'postcss': '8.5.18'
  'storybook': '10.5.4'
  'vite': '8.0.16'
  'vitest': '4.1.5'

minimumReleaseAgeExclude:
  - '@stencil/vitest@1.13.2'
  - vitest-environment-stencil@1.13.2
