linkWorkspacePackages: true
preferFrozenLockfile: true
provenance: true
saveExact: true

packages:
  - 'apps/*'
  - 'packages/*'

allowBuilds:
  '@parcel/watcher': false
  '@swc/core': true
  'core-js': true
  'esbuild': false
  'less': false
  'lmdb': false
  'msgpackr-extract': false
  'nx': true
  'rs-module-lexer': false
  'unrs-resolver': false

overrides:
  '@angular-devkit/build-angular': '21.2.9'
  '@angular-devkit/core': '21.2.9'
  '@angular-devkit/schematics': '21.2.9'
  '@custom-elements-manifest/analyzer': '0.11.0'
  '@module-federation/enhanced': '0.22.0'
  '@schematics/angular': '21.2.9'
  'ng-packagr': '21.2.3'
  'node-fetch': '3.3.2'
  'nx': '22.7.5'
  'postcss': '8.5.12'
  'storybook': '10.4.3'
  'vite': '8.0.10'
  'vitest': '4.1.5'
