name: Test & Build
description: Run linters and unit tests, build the project and finally check all E2E tests within the NX Cloud Agent.

runs:
  using: composite
  steps:
    - name: 🕵️‍♀️ Derive appropriate SHAs for base and head for `nx affected` commands
      uses: nrwl/nx-set-shas@v3

    - name: 👮🏼‍♀️ Start NX Cloud Agent
      run: npx nx-cloud start-ci-run
      shell: bash

    - name: 🩺 Run Linters and Unit Tests
      run: npx nx affected --target=test --exclude=workspace --output-style=stream-without-prefixes -- --ci --code-coverage --runInBand
      shell: bash

    - name: ⏳ Build
      run: npx nx run bee-q:storybook-build --output-style=stream-without-prefixes
      shell: bash

    - name: 🧪 Run E2E Tests (only affected)
      run: npx nx affected --target=e2e --exclude=workspace --output-style=stream-without-prefixes -- --ci --code-coverage --runInBand
      shell: bash

    - name: 📴 Stop NX Cloud Agent
      run: npx nx-cloud stop-all-agents
      shell: bash
