name: Publish to Chromatic
description: Publish the Storybook build to Chromatic cloud workspace.

runs:
  using: composite
  steps:
    - name: 📚 Publish to Chromatic
      uses: chromaui/action@v1
      env:
        CI: 'true'
      with:
        workingDir: /
        projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
        storybookBuildDir: dist/storybook/bee-q
        autoAcceptChanges: true
        exitOnceUploaded: true
        onlyChanged: true
        zip: true
