name: Get & Cache dependencies
description: Get the dependencies (via npm) and cache them

inputs:
  caching:
    description: Whether to cache the dependencies or not.
    required: false
    default: 'true'

runs:
  using: composite
  steps:
    - name: 💫 Cache dependencies
      if: inputs.caching == 'true'
      id: cache
      uses: actions/cache@v5
      with:
        path: node_modules
        key: ${{ runner.os }}-node-modules-${{ hashFiles('pnpm-lock.yaml') }}
    - name: 📦 Install dependencies
      run: pnpm install --frozen-lockfile
      shell: bash
