export const EndavaRootTheme = {
  // Fonts
  'bq-font-family': "'Roboto', sans-serif",
  'bq-white': '#fafbfb',
  'bq-black': '#030406',
  // Neutrals
  'bq-neutral-50': 'var(--bq-endava-grey-50)',
  'bq-neutral-100': 'var(--bq-endava-grey-100)',
  'bq-neutral-200': 'var(--bq-endava-grey-200)',
  'bq-neutral-300': 'var(--bq-endava-grey-300)',
  'bq-neutral-400': 'var(--bq-endava-grey-400)',
  'bq-neutral-500': 'var(--bq-endava-grey-500)',
  'bq-neutral-600': 'var(--bq-endava-grey-600)',
  'bq-neutral-700': 'var(--bq-endava-grey-700)',
  'bq-neutral-800': 'var(--bq-endava-grey-800)',
  'bq-neutral-900': 'var(--bq-endava-grey-900)',
  'bq-neutral-950': 'var(--bq-endava-grey-950)',
  'bq-neutral-1000': 'var(--bq-endava-grey-1000)',
  // Brand
  'bq-brand-light': 'var(--bq-endava-orange-100)',
  'bq-brand': 'var(--bq-endava-orange-600)',
  'bq-brand-dark': 'var(--bq-endava-orange-1000)',
  // Accent
  'bq-accent-light': 'var(--bq-endava-orange-100)',
  'bq-accent': 'var(--bq-endava-orange-600)',
  'bq-accent-dark': 'var(--bq-endava-orange-1000)',
  // Success
  'bq-success-light': 'var(--bq-green-100)',
  'bq-success': 'var(--bq-green-600)',
  'bq-success-dark': 'var(--bq-green-1000)',
  // Danger
  'bq-danger-light': 'var(--bq-corai-100)',
  'bq-danger': 'var(--bq-corai-600)',
  'bq-danger-dark': 'var(--bq-corai-1000)',
  // Warning
  'bq-warning-light': 'var(--bq-yellow-100)',
  'bq-warning': 'var(--bq-yellow-600)',
  'bq-warning-dark': 'var(--bq-yellow-1000)',
  // Info
  'bq-info-light': 'var(--bq-blue-100)',
  'bq-info': 'var(--bq-blue-600)',
  'bq-info-dark': 'var(--bq-blue-1000)',
  // Focus
  'bq-focus': 'var(--bq-endava-orange-600)',
  // Data
  'bq-data-1': 'var(--bq-brand)',
  'bq-data-2': '#af0cd8',
  'bq-data-3': '#0ca8d8',
  'bq-data-4': 'var(--bq-teal-600)',
  'bq-data-5': 'var(--bq-yellow-600)',
  'bq-data-6': 'var(--bq-orange-600)',
  'bq-data-7': 'var(--bq-blue-600)',
  'bq-data-8': 'var(--bq-red-600)',
  'bq-data-9': 'var(--bq-purple-600)',
  'bq-data-10': '#394b56',
  'bq-data-11': 'var(bq-black)',
  'bq-data-12': 'var(bq-white)',
};
